apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-anef
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-anef
    app.kubernetes.io/part-of: test-rhtap-24-app
  name: devfile-sample-code-with-quarkus-anef
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-anef
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-anef
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-24-tenant/test-rhtap-24-app/devfile-sample-code-with-quarkus-anef@sha256:7317cfb21f1c32e05a14c3d00bcca1736ee24f6b3e4032530305f75aaee55528
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
